name: Keep Replit Online

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  ping-replit:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit URL
        run: curl -s https://d98adb20-015b-4d84-8524-ded634b533d0-00-3sf1wg0ic9qpr.picard.replit.dev/ -o /dev/null
